[package]
name = "socket2"
version = "0.3.5"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/alexcrichton/socket2-rs"
homepage = "https://github.com/alexcrichton/socket2-rs"
description = """
Utilities for handling networking sockets with a maximal amount of configuration
possible intended.
"""

[package.metadata.docs.rs]
all-features = true

[target."cfg(windows)".dependencies.winapi]
version = "0.3.3"
features = ["handleapi", "ws2def", "ws2ipdef", "ws2tcpip", "minwindef"]

[target."cfg(any(unix, target_os = \"redox\"))".dependencies]
cfg-if = "0.1"
libc = { git = "https://github.com/jD91mZM2/libc" }

[target."cfg(target_os = \"redox\")".dependencies]
redox_syscall = "0.1.38"

[dev-dependencies]
tempdir = "0.3"

[features]
reuseport = []
pair = []
unix = []
