[package]
name = "socket2"
version = "0.3.14"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/alexcrichton/socket2-rs"
homepage = "https://github.com/alexcrichton/socket2-rs"
description = """
Utilities for handling networking sockets with a maximal amount of configuration
possible intended.
"""
edition = "2018"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[target."cfg(windows)".dependencies.winapi]
version = "0.3.3"
features = ["handleapi", "ws2def", "ws2ipdef", "ws2tcpip", "minwindef"]

[target."cfg(any(unix, target_os = \"redox\"))".dependencies]
cfg-if = "0.1.6"
libc = "0.2.66"

[target."cfg(target_os = \"redox\")".dependencies]
redox_syscall = "0.2.1"

[dev-dependencies]
tempdir = "0.3"

[features]
# Enable all API, even ones not available on all OSes.
all = []
