[package]
name = "socket2"
version = "0.2.1"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/alexcrichton/socket2-rs"
homepage = "https://github.com/alexcrichton/socket2-rs"
documentation = "https://docs.rs/socket2"
description = """
Utilities for handling networking sockets with a maximal amount of configuration
possible intended.
"""

[package.metadata.docs.rs]
all-features = true

[target."cfg(windows)".dependencies]
ws2_32-sys = "0.2"
winapi = "0.2"
kernel32-sys = "0.2"

[target."cfg(unix)".dependencies]
cfg-if = "0.1"
libc = "0.2.14"

[dev-dependencies]
tempdir = "0.3"

[features]
reuseport = []
pair = []
unix = []
